### ISSUE TITLE
Support efficient repeated matrix updates

### ISSUE THREAD

**Issue by garrison** [JuliaLinearAlgebra/WoodburyMatrices.jl#1]
Many numerical algorithms, including a common form of Variational Monte Carlo, operate as follows:
1. Start with an initial state described by a matrix `A`.
2. Perform an LU decomposition on `A`, saving aside its inverse (and possibly its determinant, or a log+sign of the determinant).
3. Perform some rank-k update on `A`; call the result `B`.
4. Compute the ratio `det(B)/det(A)` using `inv(A)` along with the [matrix determinant lemma](http://en.wikipedia.org/wiki/Matrix_determinant_lemma).
5. Based on some function of the ratio `det(B)/det(A)`, either "accept" or "reject" the move.  If the move is accepted, A is replaced by `B`, and the new `inv(A)` (`== inv(B)`) is determined from the Woodbury matrix identity.
6. Go to step 2 and repeat indefinitely.

(Let's leave aside the issue of numerical stability of this algorithm for now.  In practice, it can work incredibly well for hundreds of thousands of updates without recomputing the inverse from scratch, though there are times when it loses accuracy much sooner.  In case it is a helpful reference, I'll link here to the [C++ class I built that performs the above operations](https://github.com/garrison/vmc/blob/fe742aeabd34f7d3a027ea0ad94cf4f720e6a6ad/vmc-core/CeperleyMatrix.hpp).)

It is unclear to me whether code implementing the above functionality should be in the same type (currently known as `Woodbury`) or a different type.  For instance, the current `Woodbury` code never computes `inv(A)` explicitly, but this is necessary for the algorithm above to operate efficiently.  (Actually, it is unclear to me what the intended use case of the current code is, so it would help to clarify that before figuring out whether this should be a separate type.)

**Comment by timholy** [comment]
Presumably you noticed this just got copied over from base before it was deleted in https://github.com/JuliaLang/julia/pull/10024. Now that it's a package, it might actually be easier to make improvements (I can already see it needs a few).

If you look at the definition of a `Woodbury`, `A` is untyped (which needs to be fixed) precisely because it's possible to initialize `W` like this: `W = Woodbury(lufact!(A), U, C, V)`. This is based on the popular wisdom (which apparently is wrong, but I don't have time to search for the paper now) that it's better to use the factorization than it is to compute the inverse directly. However, this doesn't support your intended usage very well. I'd be amenable to making changes.

**Comment by timholy** [comment]
I've been making numerous small improvements, but nothing that changes the "core mission" of this package. For my interests, the most important use of the identity is when `A`, `U`, and `V` are all sparse, in which case the only matrices you want to compute in dense representation are `C` and `inv(inv(C) + V*(A\U))`. Hence it's important to maintain `W` in terms of a "factored" representation.

Looking at this issue again, I think the operations you describe above likely belong as a separate type. (Or perhaps just plain functions?) But I don't see any reason these couldn't be added to this package.

**Comment by garrison** [comment]
> For my interests, the most important use of the identity is when A, U, and V are all sparse

Aha, this makes a lot of sense.

I'll try to code up the other technique when I get a chance.

**Comment by timholy** [comment]
No urgency, obviously---my julia coding is on a need-to-use basis :smile:.

**Comment by timholy** [comment]
I'm going to close this, as there isn't anything that this package needs to do. PR welcome anytime, of course.
