### ISSUE TITLE
Newly added symmetric Woodbury matrix conflicts with DataArrays

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaLinearAlgebra/WoodburyMatrices.jl#13]
Commit 398eb40 on July 15, 2016 introducing support for symmetric Woodbury matrices generates the following warnings on recompile:

> WARNING: New definition 
>     +(AbstractArray, DataArrays.DataArray) at 
> ~/.julia/v0.4/DataArrays/src/operators.jl:276
> is ambiguous with: 
>     +(WoodburyMatrices.SymWoodbury, AbstractArray{T<:Any, 2}) at        ~/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:107.
> To fix, define 
>     +(WoodburyMatrices.SymWoodbury, DataArrays.DataArray{T<:Any, 2})
> before the new definition.
> WARNING: New definition 
>     +(AbstractArray, DataArrays.AbstractDataArray) at 
> ~/.julia/v0.4/DataArrays/src/operators.jl:300
> is ambiguous with: 
>     +(WoodburyMatrices.SymWoodbury, AbstractArray{T<:Any, 2}) at    ~/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:107.
> To fix, define 
>     +(WoodburyMatrices.SymWoodbury, DataArrays.AbstractDataArray{T<:Any, 2})
> before the new definition.

You may want to consider guarding the types of these operators with an abstract subtype hierarchy:

`abstract AbstractWoodbury{T} <: AbstractMatrix{T}`
`abstract AbstractSymWoodbury{T} <: AbstractWoodbury{T}`

Although I have not tried forcing a full package rebuild, or dumping, and regenerating the cache, to check if this is simply due to build order conflicts. 

General system info:

> Julia Version 0.4.5
> Commit 2ac304d (2016-03-18 00:58 UTC)
> Platform Info:
>   System: Linux (x86_64-linux-gnu)
>   CPU: Intel(R) Core(TM)2 Duo CPU     T5750  @ 2.00GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Core2)
>   LAPACK: libopenblas
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.8
> 
> XX additional packages:
> ...
> - DataArrays                    0.3.6 
>   ...
> - WoodburyMatrices              0.2.0
>   ...

**Comment by timholy** [comment]
CC @gabgoh. (You might consider clicking "watch" at the top of this page, then you'll be notified of any issues.)

**Comment by aaronsheldon** [comment]
I just tried my suggestion - it didn't help.

Out of curiosity any reason the + and scalar \* operator overloading wouldn't equally apply to the general Woodbury matrices, and not just the symmetric case? If so then shouldn't it be defined for StridedVecOrMat, instead of AbstractMatrix? In particular:

![woodury](https://cloud.githubusercontent.com/assets/2558919/17086075/286bd80e-51a6-11e6-8078-8e61dc6de2eb.png)

As well, if overloading was moved to the general Woodbury (except for symmetric {op} symmetric), then a type promotion would be needed to convert the symmetric case to the general case.

...ugh type logic makes my head hurt...I think these are the minimal definitions, assuming the compiler matches the tightest fit preferentially...

Type promotion :
- matrix, any Woodbury -> matrix & promote type parameters
- ~~data array, any Woodbury -> data array & promote type parameters~~

_not only would this require importing data arrays, yuck, the responsibility for who should resolve the overloading conflicts is unclear, should it be Woodbury or data array?_
- any Woodbury, any Woodbury -> Woodbury & promote type parameters
- symmetric, symmetric -> symmetric & promote type parameters

Addition mashing:
- matrix, Woodbury -> Woodbury (adding to the first term)
- matrix, symmetric -> symmetric (adding to the first term)

_these two methods would have to be defined because they are opposite of what would occur through type promotion_
- ~~data array, any Woodbury -> data array (full Woodbury to handle nulls in data array)~~

_should be covered by type promotion_
- any Woodbury, any Woodbury -> Woodbury (using formula)
- symmetric, symmetric -> symmetric (using formula)

Matrix multiplication mashing:
- ~~matrix, any Woodbury -> Woodbury (potential for type indecision without choosing which one is full)~~
- dense, any Woodbury -> Woodbury
- sparse, any Woodbury -> Woodbury

_leave Woodbury-Woodbury products undefined to force the choice of which one contains the factors and which one is full. The product of two Woodbury matrices is a Woodbury matrix, but it has many possible representations, according to the division of terms into the sum and the factors (is there a definition of a minimal representation? Is there an algorithm for choosing a minimal representation?)_
- ~~data array, any Woodbury -> data array (have to check if data array supports this, because of nulls)~~

_not defined for data arrays, only works element wise, which would be covered by type promotion_

Squaring mashing:
- symmetric -> symmetric

Scalar multiplication mashing, and matrix inversion should preserve type.

**Comment by gabgoh** [comment]
hey, thanks for pointing this out.

It seems like implementing +(A::MyType, B::AbstractMatrix) is bad practice in general as it gives rise to ambiguities above.

I think a workaround would be, as you suggest, to only allow the addition of 2 symwoodbury/woodbury matrices, and forcing a convert from an AbstractMatrix to a SymWoodbury/Woodbury (of the form A + some empty matrices). The overhead should be negligible.

if there are no objections @timholy i'll go ahead and do this.

**Comment by timholy** [comment]
Sounds fine. Also note that the warnings are gone on julia 0.5. If you actually try to add a `SymWoodbury` and a `DataArray`, you'll get an error (unless you first go to the effort to define what you want to happen with that operation). But it won't clutter your display about a hypothetical problem that may never arise in practice.

So I'm also fine with leaving this like it is.

**Comment by aaronsheldon** [comment]
Ah shoot...then 0.5 could break Gadfly.

Gadfly requires DataFrames and KernelDensities, but DataFrames requires DataArrays, and KernelDensities requires Grid which in turn requires WoodburyMatrices.

**Comment by gabgoh** [comment]
ok ill do this but its on the backburner. i'll keep an eye out if this package breaks anything.

**Comment by diegozea** [comment]
**StatPlots** also gives this warnings in Julia 0.4.5:

```
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /home/dzea/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /home/dzea/.julia/v0.4/DataArrays/src/operators.jl:276.
To fix, define 
    +(DataArrays.DataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /home/dzea/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.AbstractDataArray, AbstractArray) at /home/dzea/.julia/v0.4/DataArrays/src/operators.jl:300.
To fix, define 
    +(DataArrays.AbstractDataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
```

**Comment by timholy** [comment]
> Ah shoot...then 0.5 could break Gadfly.

How? The whole point is to make it _easier_ to use packages that have an in-principle but not in-practice conflict. In julia 0.4, the strategy is
- check for ambiguities when functions are being defined/loaded
- warn if an ambiguity is detected (note: even if a more specific ambiguity-resolving method is defined later, that doesn't prevent the warning because they're issued as each function gets defined)
- if the user ignores the warning and issues an ambiguous call, **pick one of the candidate methods at random** and execute it (not truly random, but I don't think anyone would call the choice "predictable" either; it depends on the order in which functions are defined/packages loaded, etc)

In julia 0.5 the strategy is
- keep track of potential ambiguities when functions are being defined, but remain silent
- during JIT-compilation, scan for any potential ambiguities given the actual types of the arguments. (Note that later-defined methods can eliminate the ambiguity by being more specific, so order of definition no longer matters.) If it really is an ambiguous call, issue an error rather than picking something at random.

To me the latter strategy seems superior in every way. The worst thing about the 0.4 strategy is that while there might be an ambiguity for `+` when using an `Array{DateTime}` and an `Image{RGB}`, I can't imagine why I'd ever try adding those two things together. So the ambiguity warning is worse than useless: if you have enough of them, they hide messages that you should worry about.

Disclaimer: I was the one who implemented this in julia 0.5, so of course I'm biased.

**Comment by aaronsheldon** [comment]
I agree the strategy in 0.5 is clearly better - it is just coming with some growing pains for package maintainers.

I also agree the it is preferable for package maintainers to overload operators conservatively, because the user should have to decide how to resolve conflicting definitions between packages. But this is going to have to be a message broadly disseminated to package maintainers: carefully audit your overloading.

**Comment by timholy** [comment]
> I agree the strategy in 0.5 is clearly better - it is just coming with some growing pains for package maintainers.

I'm still not sure I understand what a package maintainer needs to do, can you explain? Keep in mind that you'll trigger an error only if you try to add a DataArray to a SymWoodbury. Is that something you plan on doing, or expect to crop up naturally?

**Comment by aaronsheldon** [comment]
Nope you're right I wrote that backwards, it is 0.4 that has the pains. Fail on actually doing something bad is better than kind of fail/warn on the potential of doing something bad.

I guess what I was trying to express was my own take away lesson: when developing new types and overloading to carefully consider the scope of the overloading; that is how far up the type tree to climb. In particular before you start to loose a "cultural" sense of certainty over what the developers of those types are expressing. So looking at the type tree I can, as a coder, infer a certain amount of stability in the generics around Dense Matrix and Sparse Matrix, but climbing all the way up to Abstract Array the generics get much less certain.

I don't know if that even makes sense, it reads awfully vague.

_I consider that I have to reason about types in this manner a testament to the strength of the Julia; rather than spending time trying to find ugly coercion hacks. The more time I can spend coding abstract relationships and the less time I spend mashing datatype X into datatype Y the happier I am._

**Comment by aaronsheldon** [comment]
I'm satisfied with the 0.5 explanation - closing

**Comment by Evizero** [comment]
cool stuff. I was just investigating how to get rid of

```
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /home/csto/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(Images.AbstractImageDirect, AbstractArray) at /home/csto/.julia/v0.4/Images/src/algorithms.jl:18.
To fix, define 
    +(Images.AbstractImageDirect{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
```

Very pleased that it takes care of itself in a couple of days. Wish all my problems were this easy 👍
