### ISSUE TITLE
error showing Woodbury matrix

### ISSUE THREAD

**Issue by randy3k** [JuliaLinearAlgebra/WoodburyMatrices.jl#19]
```Julia
n = 5
d = 1 .+ rand(n)
dl = -rand(n-1)
du = -rand(n-1)
T = Tridiagonal(dl, d, du)
U = sprandn(n,2,0.2)
V = sprandn(2,n,0.2)
C = randn(2,2)
W = Woodbury(T, U, C, V)
```

```
julia> W = Woodbury(T, U, C, V)
5×5 WoodburyMatrices.Woodbury{Float64,Tridiagonal{Float64},SparseMatrixCSC{Float64,Int64},SparseMatrixCSC{Float64,Int64},Array{Float64,2},Array{Float64,2}}:
Error showing value of type WoodburyMatrices.Woodbury{Float64,Tridiagonal{Float64},SparseMatrixCSC{Float64,Int64},SparseMatrixCSC{Float64,Int64},Array{Float64,2},Array{Float64,2}}:
ERROR: indexing not defined for WoodburyMatrices.Woodbury{Float64,Tridiagonal{Float64},SparseMatrixCSC{Float64,Int64},SparseMatrixCSC{Float64,Int64},Array{Float64,2},Array{Float64,2}}
```

It is because `AbstractArray` dispatches `showarray` in default:
https://github.com/JuliaLang/julia/blob/f56fe1c7c5a191583af62cb38df061fec8958fde/base/replutil.jl#L140

Possible solution: we may need to define
```
show(io::IO, ::MIME"text/plain", X::Woodbury) = show(io, X)
```
similar to SparseMatrix
https://github.com/JuliaLang/julia/blob/f56fe1c7c5a191583af62cb38df061fec8958fde/base/sparse/sparsematrix.jl?utf8=✓#L129

**Comment by randy3k** [comment]
Also, there is no `show` function defined for `SymWoodbury`.

**Comment by timholy** [comment]
There's an argument to be made that it's a mistake to make these subtypes of `AbstractArray`. They can be thought of as factorization objects, and our other factorizations are not subtypes of `AbstractArray`. Then the default "show any object" method would work fine.

The question is, what would it break if we didn't subtype them this way?
